# -*- coding: utf-8 -*-
"""Desafio_Target_Sistemas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K6d6JRXr38MeszWRaYtEf-T4rmHk8j2d
"""

# 1) Dado a sequência de Fibonacci, onde se inicia por 0 e 1 e o próximo valor sempre será a soma dos 2 valores anteriores
 #  (exemplo: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34...), escreva um programa na linguagem que desejar onde, informado um número,
 #  ele calcule a sequência de Fibonacci e retorne uma mensagem avisando se o número informado pertence ou não a sequência.

# IMPORTANTE: Esse número pode ser informado através de qualquer entrada de sua preferência ou pode ser previamente definido no código;


def pertence_fibonacci(n):
    # Sequência de Fibonacci inicial
    a, b = 0, 1
    # Verifica se o número é 0 ou 1, que pertencem à sequência
    if n == 0 or n == 1:
        return True

    # Calcula os próximos números da sequência de Fibonacci
    while b <= n:
        if b == n:
            return True
        a, b = b, a + b

    # Se o número não foi encontrado na sequência, retorna False
    return False

# Entrada do número a ser verificado
numero = int(input("Informe um número para verificar se pertence à sequência de Fibonacci: "))

# Chama a função e exibe o resultado
if pertence_fibonacci(numero):
    print(f"O número {numero} pertence à sequência de Fibonacci.")
else:
    print(f"O número {numero} não pertence à sequência de Fibonacci.")

# 2) Escreva um programa que verifique, em uma string, a existência da letra ‘a’, seja maiúscula ou minúscula, além de informar a quantidade de vezes em que ela ocorre.

#   IMPORTANTE: Essa string pode ser informada através de qualquer entrada de sua preferência ou pode ser previamente definida no código;


def contar_letra_a(texto):
    # Converte o texto para minúsculas e conta as ocorrências da letra 'a'
    ocorrencias = texto.lower().count('a')

    # Verifica se a letra 'a' aparece na string
    if ocorrencias > 0:
        print(f"A letra 'a' aparece {ocorrencias} vezes na string.")
    else:
        print("A letra 'a' não aparece na string.")

# Entrada do texto a ser verificado
texto = input("Digite uma string para verificar a ocorrência da letra 'a': ")

# Chama a função e exibe o resultado
contar_letra_a(texto)